"""Create initial tables

Revision ID: 782743638d2b
Revises: 
Create Date: 2025-11-11 18:21:02.428010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
# revision identifiers, used by Alembic.
revision: str = '782743638d2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('causal_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cause_memory_id', sa.UUID(), nullable=False),
    sa.Column('effect_memory_id', sa.UUID(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('inferred_at', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_causal_links_cause_memory_id'), 'causal_links', ['cause_memory_id'], unique=False)
    op.create_index(op.f('ix_causal_links_effect_memory_id'), 'causal_links', ['effect_memory_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('assistant_message', sa.String(), nullable=False),
    sa.Column('cognitive_plan', sa.JSON(), nullable=True),
    sa.Column('memories_used', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_conversation_id'), 'interactions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_interactions_timestamp'), 'interactions', ['timestamp'], unique=False)
    op.create_table('episodic_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('attention_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodic_memories_importance'), 'episodic_memories', ['importance'], unique=False)
    op.create_index(op.f('ix_episodic_memories_timestamp'), 'episodic_memories', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodic_memories_timestamp'), table_name='episodic_memories')
    op.drop_index(op.f('ix_episodic_memories_importance'), table_name='episodic_memories')
    op.drop_table('episodic_memories')
    op.drop_index(op.f('ix_interactions_timestamp'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_conversation_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_causal_links_effect_memory_id'), table_name='causal_links')
    op.drop_index(op.f('ix_causal_links_cause_memory_id'), table_name='causal_links')
    op.drop_table('causal_links')
    op.execute("DROP EXTENSION IF EXISTS vector")

    # ### end Alembic commands ###
