"""Add procedural_memories table

Revision ID: 26f54c313fa2
Revises: 68851d6e6b5a
Create Date: 2025-11-11 20:31:31.428427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26f54c313fa2'
down_revision: Union[str, Sequence[str], None] = '68851d6e6b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedural_memories', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('procedural_memories', 'cognitive_plan',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('procedural_memories', 'success_criteria',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('procedural_memories', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procedural_memories', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('procedural_memories', 'success_criteria',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('procedural_memories', 'cognitive_plan',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('procedural_memories', 'created_at')
    # ### end Alembic commands ###
