"""Add raw_observations table

Revision ID: 68851d6e6b5a
Revises: 782743638d2b
Create Date: 2025-11-11 20:26:10.763615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
# revision identifiers, used by Alembic.
revision: str = '68851d6e6b5a'
down_revision: Union[str, Sequence[str], None] = '782743638d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedural_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('task_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('cognitive_plan', sa.JSON(), nullable=False),
    sa.Column('success_criteria', sa.String(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('related_concepts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedural_memories_task_description'), 'procedural_memories', ['task_description'], unique=False)
    op.create_table('raw_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_observations_source'), 'raw_observations', ['source'], unique=False)
    op.create_index(op.f('ix_raw_observations_status'), 'raw_observations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_observations_status'), table_name='raw_observations')
    op.drop_index(op.f('ix_raw_observations_source'), table_name='raw_observations')
    op.drop_table('raw_observations')
    op.drop_index(op.f('ix_procedural_memories_task_description'), table_name='procedural_memories')
    op.drop_table('procedural_memories')
    # ### end Alembic commands ###
